# Carregamento dos dados referentes ao artigo 'The AV SSVEP Dataset'

In [1]:
# Imports
from scipy.io import loadmat
import numpy as np
import math

#Nota na hora de salvar os dados deixar tipo, 4, 21, 15360 

## Carregamento dos dados Single

In [2]:
# Pré carregamento

avi_data = list()
for i in range(1, 5):
    avi_data.append(loadmat(f"../dataset/sc/DataSet_A_2/single/Sub{i}_singletarget.mat"))
    
#print(data[0]['Data'])
#print(data[0]['Data'][0][0][-1])
#print(data[0]['Data'][0][0][0].shape)
#print(data[0]['Data'][0][0][-1].shape)

In [3]:
# extração direta dos dados

X_data = [d['Data'][0][0][0] for d in avi_data]
y_data = [d['Data'][0][0][1] for d in avi_data]

print("Divisão dos dados:")
for data in X_data:
    print(data.shape)

print("\nDivisão dos rótulos (sequências):")
for data in y_data:
    print(data)

Divisão dos dados:
(15360, 27)
(15360, 26)
(15360, 21)
(15360, 21)

Divisão dos rótulos (sequências):
[[10.  10.  10.  12.  12.  12.   6.5  6.5  6.5  6.   6.   6.   6.   6.
   6.   7.5  7.5  7.5  7.   7.   7.   8.2  8.2  8.2  9.3  9.3  9.3]]
[[10.  10.  10.   6.5  6.5  6.5  6.5  6.   6.   6.   7.5  7.5  7.5  7.
   7.   7.   7.   7.   7.   8.2  8.2  8.2  8.2  9.3  9.3  9.3]]
[[10.  10.  10.   6.5  6.5  6.5  6.   6.   6.   7.5  7.5  7.5  7.   7.
   7.   8.2  8.2  8.2  9.3  9.3  9.3]]
[[10.  10.  10.   6.5  6.5  6.5  6.   6.   6.   7.5  7.5  7.5  7.   7.
   7.   8.2  8.2  8.2  9.3  9.3  9.3]]


In [4]:

dados = list()
labels = list()

dados.append(X_data[0][:, list(set(range(27)) - set([3, 4, 5, 12, 13, 14]))])
labels.append(y_data[0][:, list(set(range(27)) - set([3, 4, 5, 12, 13, 14]))])
        
dados.append(X_data[1][:, list(set(range(26)) - set([6, 16, 17, 18, 22]))])
labels.append(y_data[1][:, list(set(range(26)) - set([6, 16, 17, 18, 22]))])
        
dados.append(X_data[2])
labels.append(y_data[2])
        
dados.append(X_data[3])
labels.append(y_data[3])

data = np.array(dados)
label = np.array(labels)
np.save("../dataset/sc/DataSet_A_2/single/data_unificada.npy", data)
np.save("../dataset/sc/DataSet_A_2/single/label_unificada.npy", label)

## Carregamento dos dados multi


In [5]:
# Pré carregamento

avi_data = list()
j = 1
k = 1
for i in range(1, 11):
    if j == 3:
        j = 1
    avi_data.append(loadmat(f"../dataset/sc/DataSet_A_2/multi/Sub{math.ceil(i / 2)}_{j}_multitarget.mat"))
    j += 1

In [6]:
# extração direta dos dados
# 8192 / 512 == 16 segundos em cada frequencia
#Transpor os dados para que fique (10, 8192)
X_data = [d['Data'][0][0][7].T for d in avi_data]
y_data = [d['Data'][0][0][8][0] for d in avi_data]

print("Divisão dos dados:")
for data in X_data:
    print(data.shape)

print("\nDivisão dos rótulos (sequências):")
for data in y_data:
    print(data)

Divisão dos dados:
(10, 8192)
(10, 8192)
(10, 8192)
(10, 8192)
(10, 8192)
(10, 8192)
(10, 8192)
(10, 8192)
(10, 8192)
(10, 8192)

Divisão dos rótulos (sequências):
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]


In [7]:
dados = list()
labels = list()

for i in range(10):
    dados.append(X_data[i])
    labels.append(y_data[i])

data = np.array(dados)
label = np.array(labels)

np.save("../dataset/sc/DataSet_A_2/multi/data_unificada.npy", data)
np.save("../dataset/sc/DataSet_A_2/multi/label_unificada.npy", label)

# Carregamento do DataSet Beta (sujeito 12)

In [ ]:
data = loadmat("../dataset/beta/S12.mat")

In [ ]:
data