# Carregamento dos dados referentes ao artigo 'The AV SSVEP Dataset'

In [31]:
# Imports
from scipy.io import loadmat
import numpy as np
import math

#Nota na hora de salvar os dados deixar tipo, 4, 21, 15360 

## Carregamento dos dados Single

In [32]:
# Pré carregamento

avi_data = list()
for i in range(1, 5):
    avi_data.append(loadmat(f"../dataset/sc/DataSet_A_2/single/Sub{i}_singletarget.mat"))
    
#print(data[0]['Data'])
#print(data[0]['Data'][0][0][-1])
#print(data[0]['Data'][0][0][0].shape)
#print(data[0]['Data'][0][0][-1].shape)

In [33]:
# extração direta dos dados

X_data = [d['Data'][0][0][0] for d in avi_data]
y_data = [d['Data'][0][0][1] for d in avi_data]

print("Divisão dos dados:")
for data in X_data:
    print(data.shape)

print("\nDivisão dos rótulos (sequências):")
for data in y_data:
    print(data)

In [34]:
X_data[0].shape

(15360, 27)

In [35]:
teste_data = X_data[0][:, list(set(range(27)) - set([3, 4, 5, 12, 13, 14]))]
teste_data.shape

(15360, 21)

In [36]:

dados = list()
labels = list()

dados.append(X_data[0][:, list(set(range(27)) - set([3, 4, 5, 12, 13, 14]))])
labels.append(y_data[0][:, list(set(range(27)) - set([3, 4, 5, 12, 13, 14]))])
        
dados.append(X_data[1][:, list(set(range(26)) - set([6, 16, 17, 18, 22]))])
labels.append(y_data[1][:, list(set(range(26)) - set([6, 16, 17, 18, 22]))])
        
dados.append(X_data[2])
labels.append(y_data[2])
        
dados.append(X_data[3])
labels.append(y_data[3])

data = np.array(dados)
label = np.array(labels)
np.save("../dataset/sc/DataSet_A_2/single/data_unificada.npy", dados)
np.save("../dataset/sc/DataSet_A_2/single/label_unificada.npy", labels)

## Carregamento dos dados multi


In [37]:
# Pré carregamento

avi_data = list()
j = 1
k = 1
for i in range(1, 11):
    if j == 3:
        j = 1
    avi_data.append(loadmat(f"../dataset/sc/DataSet_A_2/multi/Sub{math.ceil(i / 2)}_{j}_multitarget.mat"))
    j += 1

In [38]:
# Pré carregamento

data = list()
j = 1
k = 1
for i in range(1, 11):
    if j == 3:
        j = 1
    data.append(loadmat(f"../dataset/sc/DataSet_A_2/multi/Sub{math.ceil(i / 2)}_{j}_multitarget.mat"))
    #print(math.ceil(i / 2), j)
    j += 1
    
    

#print(data[0]['Data'])
#print(data[0]['Data'][0][0][-1])
#for i, item in enumerate(data[0]['Data'][0][0]):
#    print(i, item)
    #print(data[0]['Data'][0][0])
print(data[1]['Data'][0][0][7].shape)
print(data[1]['Data'][0][0][8][0].shape)

(8192, 10)
(10,)


In [39]:
# extração direta dos dados
# 8192 / 512 == 16 segundos em cada frequencia
#Transpor os dados para que fique (10, 8192)
X_data = [d['Data'][0][0][7].T for d in avi_data]
y_data = [d['Data'][0][0][8][0] for d in avi_data]

print("Divisão dos dados:")
for data in X_data:
    print(data.shape)

print("\nDivisão dos rótulos (sequências):")
for data in y_data:
    print(data)

Divisão dos dados:
(10, 8192)
(10, 8192)
(10, 8192)
(10, 8192)
(10, 8192)
(10, 8192)
(10, 8192)
(10, 8192)
(10, 8192)
(10, 8192)

Divisão dos rótulos (sequências):
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]


In [40]:
dados = list()
labels = list()

for i in range(10):
    dados.append(X_data[i])
    labels.append(y_data[i])

data = np.array(dados)
label = np.array(labels)

print(data.shape)
print(label.shape)
np.save("../dataset/sc/DataSet_A_2/multi/data_unificada.npy", dados)
np.save("../dataset/sc/DataSet_A_2/multi/label_unificada.npy", labels)

# Carregamento do DataSet Beta (sujeito 12)

In [41]:
data = loadmat("../dataset/beta/S12.mat")

In [42]:
data

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Mon Mar 21 10:16:47 2016',
 '__version__': '1.0',
 '__globals__': [],
 'data': array([[[[-1.52248354e+01, -2.64133091e+01, -6.08993416e+01,
            2.86680555e+00, -1.02286911e+02, -4.23872070e+01],
          [ 8.22766495e+00,  4.17269592e+01, -2.06432247e+01,
           -3.62071533e+01, -3.38756027e+01, -8.65305233e+00],
          [-8.81779556e+01, -3.64715195e+00, -5.78999825e+01,
           -1.81573257e+01, -9.85365601e+01, -2.10711327e+01],
          ...,
          [ 7.15433655e+01,  3.62132339e+01, -3.21245308e+01,
           -2.13716769e+00, -5.57121086e+01,  1.39468946e+01],
          [-5.48752708e+01, -5.86311035e+01, -7.02925568e+01,
           -7.73214626e+00, -9.20802784e+00,  3.49117160e+00],
          [ 3.37851601e+01, -1.13140593e+01, -3.22216492e+01,
            5.89226055e+00,  4.77906189e+01, -5.13424339e+01]],
 
         [[-8.77730274e+00, -2.33745098e+01, -5.77996025e+01,
           -1.91316090e