# Carregamento dos dados referentes ao artigo 'The AV SSVEP Dataset'

In [1]:
# Imports
from scipy.io import loadmat
import numpy as np
import math

#Nota na hora de salvar os dados deixar tipo, 4, 21, 15360 

## Carregamento dos dados Single

In [ ]:
# Pré carregamento

avi_data = list()
for i in range(1, 5):
    avi_data.append(loadmat(f"../dataset/sc/DataSet_A_2/single/Sub{i}_singletarget.mat"))
    
#print(data[0]['Data'])
#print(data[0]['Data'][0][0][-1])
#print(data[0]['Data'][0][0][0].shape)
#print(data[0]['Data'][0][0][-1].shape)

In [ ]:
# extração direta dos dados

X_data = [d['Data'][0][0][0] for d in avi_data]
y_data = [d['Data'][0][0][1] for d in avi_data]

print("Divisão dos dados:")
for data in X_data:
    print(data.shape)

print("\nDivisão dos rótulos (sequências):")
for data in y_data:
    print(data)

In [ ]:

dados = list()
labels = list()

dados.append(X_data[0][:, list(set(range(27)) - set([3, 4, 5, 12, 13, 14]))])
labels.append(y_data[0][:, list(set(range(27)) - set([3, 4, 5, 12, 13, 14]))])
        
dados.append(X_data[1][:, list(set(range(26)) - set([6, 16, 17, 18, 22]))])
labels.append(y_data[1][:, list(set(range(26)) - set([6, 16, 17, 18, 22]))])
        
dados.append(X_data[2])
labels.append(y_data[2])
        
dados.append(X_data[3])
labels.append(y_data[3])

data = np.array(dados)
label = np.array(labels)
np.save("../dataset/sc/DataSet_A_2/single/data_unificada.npy", data)
np.save("../dataset/sc/DataSet_A_2/single/label_unificada.npy", label)

## Carregamento dos dados multi


In [27]:
# Pré carregamento

avi_data = list()
j = 1
k = 1
for i in range(1, 11):
    if j == 3:
        j = 1
    avi_data.append(loadmat(f"../dataset/sc/DataSet_A_2/multi/Sub{math.ceil(i / 2)}_{j}_multitarget.mat"))
    j += 1

In [28]:
# extração direta dos dados
# 8192 / 512 == 16 segundos em cada frequencia
#Transpor os dados para que fique (10, 8192)
X_data = [d['Data'][0][0][7].T for d in avi_data]
y_data = [d['Data'][0][0][8][0] for d in avi_data]

print("Divisão dos dados:")
for data in X_data:
    print(data.shape)

print("\nDivisão dos rótulos (sequências):")
for data in y_data:
    print(data)

Divisão dos dados:
(10, 8192)
(10, 8192)
(10, 8192)
(10, 8192)
(10, 8192)
(10, 8192)
(10, 8192)
(10, 8192)
(10, 8192)
(10, 8192)

Divisão dos rótulos (sequências):
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]


In [29]:
dados = list()
labels = list()

for i in range(10):
    dados.append(X_data[i])
    labels.append(y_data[i])

data = np.array(dados)
label = np.array(labels)

np.save("../dataset/sc/DataSet_A_2/multi/data_unificada.npy", data)
np.save("../dataset/sc/DataSet_A_2/multi/label_unificada.npy", label)

In [31]:
label.shape

(10, 10)

In [30]:
data.shape

(10, 10, 8192)

# Carregamento do DataSet Beta (sujeito 12)

In [2]:
data = loadmat("../dataset/beta/S12.mat")
#label = loadmat("../dataset/beta/Freq_Phase.mat")

In [33]:
data

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Wed Oct 20 11:40:49 2021',
 '__version__': '1.0',
 '__globals__': [],
 'data': array([[(array([[[[ 5.81738204e+00,  8.89122733e+00,  4.25316605e+00, ...,
                    2.69433786e+00, -1.38120596e-01, -9.69752526e-01],
                  [ 1.77636866e+00,  2.57691521e+00,  1.47927202e+01, ...,
                    1.26801229e+00, -9.06331945e+00, -4.08901168e+00],
                  [ 2.71225640e+00, -5.06397305e+00,  5.21623983e+00, ...,
                   -6.11287865e+00, -8.25292221e+00,  6.27895782e+00],
                  [-2.22625414e+00,  1.06030355e+02,  5.56040318e+00, ...,
                    1.12038278e+02,  5.48539989e-01, -3.82851948e+00]],
 
                 [[-2.93133869e-02,  8.76359235e+00,  3.27442573e+00, ...,
                   -6.14742056e+00,  2.81153063e+00, -5.35434458e+00],
                  [ 1.64483747e+00,  2.66078008e-02,  9.37085162e+00, ...,
                   -2.34151968e-01, -4.00841

In [44]:
data['data'][0][0][0] # dados
#64 canais


array([[[[ 5.81738204e+00,  8.89122733e+00,  4.25316605e+00, ...,
           2.69433786e+00, -1.38120596e-01, -9.69752526e-01],
         [ 1.77636866e+00,  2.57691521e+00,  1.47927202e+01, ...,
           1.26801229e+00, -9.06331945e+00, -4.08901168e+00],
         [ 2.71225640e+00, -5.06397305e+00,  5.21623983e+00, ...,
          -6.11287865e+00, -8.25292221e+00,  6.27895782e+00],
         [-2.22625414e+00,  1.06030355e+02,  5.56040318e+00, ...,
           1.12038278e+02,  5.48539989e-01, -3.82851948e+00]],

        [[-2.93133869e-02,  8.76359235e+00,  3.27442573e+00, ...,
          -6.14742056e+00,  2.81153063e+00, -5.35434458e+00],
         [ 1.64483747e+00,  2.66078008e-02,  9.37085162e+00, ...,
          -2.34151968e-01, -4.00841641e+00, -1.95154486e+00],
         [-2.62288224e-01, -3.24076606e+00, -8.15461341e-01, ...,
          -1.33120843e+01, -8.48597839e+00,  7.43932737e+00],
         [ 1.01165981e+01,  1.17537945e+02,  4.59560981e-01, ...,
           1.14854856e+02,  2.119630

In [51]:
data['data'][0][0][1][0][0][-6]
#64 canais


array([[ 8.6,  8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4, 10.6,
        10.8, 11. , 11.2, 11.4, 11.6, 11.8, 12. , 12.2, 12.4, 12.6, 12.8,
        13. , 13.2, 13.4, 13.6, 13.8, 14. , 14.2, 14.4, 14.6, 14.8, 15. ,
        15.2, 15.4, 15.6, 15.8,  8. ,  8.2,  8.4]])

In [52]:
X = np.array(data['data'][0][0][0])
y = np.array(data['data'][0][0][1][0][0][-6])

print(X.shape)
print(y.shape)
np.save("../dataset/beta/data_unificada.npy", X)
np.save("../dataset/beta/label_unificada.npy", y)

# 40 x 4

(64, 750, 4, 40)
(1, 40)
